add paging support to trustedDomains get endpoint
blackboard/kloudless-node pull request #2
Opened 2018-02-09 18:35 UTC by ptsteele

This is needed to properly consume the trustedDomain get all endpoint

2018-02-10 18:27 UTC, mtheoryx requested changes

2018-02-10 18:27 UTC, mtheoryx commented on lib/methods/trustedDomains.js
> +            this.path = data['application_id'] + '/trusted_domains?page=' + data['page'];
Is this going to work with the conversion to use offset and limit? I suspect not.

2018-02-12 13:22 UTC, ptsteele commented on lib/methods/trustedDomains.js
> +            this.path = data['application_id'] + '/trusted_domains?page=' + data['page'];
This is for talking to the Kloudless api itself, which utilizes `page` as the query string.

2018-02-12 14:26 UTC, mtheoryx approved these changes

2018-02-12 17:59 UTC, justinm approved these changes

2018-02-12 18:21 UTC, merged